# Generated by Django 2.2.9 on 2021-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
